mehdie_commerce_products:
    path:     /products/{page}
    defaults: 
        _controller: MEHDIECommerceBundle:Product:index
        page: 1
    requirements:
        page: \d*

mehdie_commerce_products_add:
    path:     /products/add
    defaults: { _controller: MEHDIECommerceBundle:Product:add }
    
mehdie_commerce_products_edit:
    path:     /products/edit/{id}
    defaults: { _controller: MEHDIECommerceBundle:Product:edit }
    requirements:
        id: \d+
    
mehdie_commerce_products_delete:
    path:     /products/delete/{id}
    defaults: { _controller: MEHDIECommerceBundle:Product:delete }
    requirements:
        id: \d+
        
mehdie_commerce_products_view:
    path:     /products/view/{id}
    defaults: { _controller: MEHDIECommerceBundle:Product:view }
    requirements:
        id: \d+
        
mehdie_commerce_products_editQuantite:
    path:     /products/editQuantite/{id}
    defaults: { _controller: MEHDIECommerceBundle:Product:editQuantite }
    requirements:
        id: \d+
        
mehdie_commerce_category:
    path:     /category
    defaults: { _controller: MEHDIECommerceBundle:Category:index }

mehdie_commerce_category_add:
    path:     /category/add
    defaults: { _controller: MEHDIECommerceBundle:Category:add }
    
mehdie_commerce_category_edit:
    path:     /category/edit/{id}
    defaults: { _controller: MEHDIECommerceBundle:Category:edit }
    requirements:
        id: \d+
    
mehdie_commerce_category_delete:
    path:     /category/delete/{id}
    defaults: { _controller: MEHDIECommerceBundle:Category:delete }
    requirements:
        id: \d+
        
mehdie_commerce_basket_index:
    path:   /basket
    defaults: { _controller: MEHDIECommerceBundle:Basket:index }
    
mehdie_commerce_basket_deleteProd:
    path:   /basket/delete/{id}
    defaults: { _controller: MEHDIECommerceBundle:Basket:deleteProd }
    requirements:
        id: \d+
        
mehdie_commerce_basket_editQty:
    path:   /basket/editQty/{id}
    defaults: { _controller: MEHDIECommerceBundle:Basket:editQty }
    requirements:
        id: \d+
        
mehdie_commerce_basket_order:
    path:   /basket/order
    defaults: { _controller: MEHDIECommerceBundle:Basket:order }
    
mehdie_commerce_commande_index:
    path:   /commande
    defaults: { _controller: MEHDIECommerceBundle:Commande:index }