MEHDI\ECommerceBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: MEHDI\ECommerceBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
