MEHDI\ECommerceBundle\Entity\Commande:
    type: entity
    table: null
    repositoryClass: MEHDI\ECommerceBundle\Repository\CommandeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateCommande:
            type: datetime
        montant:
            type: decimal
            precision: 10
            scale: '3'
        etat:
            type: string
            length: 255
    manyToOne:
            user:
                targetEntity: MEHDI\UserBundle\Entity\User    
    manyToMany:        
            products:
                targetEntity: Product
    lifecycleCallbacks: {  }
