MEHDI\ECommerceBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: MEHDI\ECommerceBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: 255
        prixUnitaire:
            type: decimal
            precision: 10
            scale: '2'
        quantiteRestante:
            type: integer
        dateAjout:
            type: datetime
        evaluation:
            type: decimal
            precision: 10
            scale: '2'
        description:
            type: text
        client:
            type: MEHDI\UserBundle\Entity\User
            manyToOne:
                user:
                    targetEntity: User
                    joinColumn:
                        name: user_id 
                        referencedColumnName: id
        category:
            type: MEHDI\ECommerceBundle\Entity\Category
            manyToOne:
                category:
                    targetEntity: Category
                    joinColumn:
                        name: category_id 
                        referencedColumnName: id   
        image:
            type: MEHDI\ECommerceBundle\Entity\Image
            oneToOne:
                image:
                    targetEntity: Image
                    joinColumn:
                        name: image_id 
                        referencedColumnName: id                    
    lifecycleCallbacks: {  }
