mehdi_core_homepage:
    path:     /{page}
    defaults:  
        _controller: MEHDICoreBundle:Core:index 
        page: 1
    requirements:
        page: \d+
        
mehdi_core_homeView:
    path:   /view/{id}
    defaults:   { _controller: MEHDICoreBundle:Core:homeView }
    requirements:
        id: \d+

mehdi_core_addinBasket:
    path:   /addinBasket
    defaults:   { _controller: MEHDICoreBundle:Core:addInBasket }

