user_authentication:
    path: /authentication
    defaults: {_controller:UserBundle:User:authentication}

user_add:
    path: /add
    defaults: {_controller:UserBundle:User:add}
    
user_update:
    path: /update/{id}
    defaults: {_controller:UserBundle:User:update}
    requirements:
        id: \d+
        
user_delete:
    path: /delete/{id}
    defaults: {_controller:UserBundle:User:delete}
    requirements:
        id: \d+

user_listing:
    path: /listing
    defaults: {_controller:UserBundle:User:listing}
    