<?php

namespace MEHDI\ECommerceBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function countProductWithCategory($categoryId){
		$qb=$this->createQueryBuilder('p');//permet de construire une requête
		$qb->select('count(p.id)');
		$qb->join('p.category','c');
		$qb->where('c.id = :id');
		
		return $qb
			->getQuery()
			->setParameter('id',$categoryId)
			->getSingleScalarResult();
		
	}
	
	
	
}
